# Generated by Django 4.1.5 on 2023-03-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.BooleanField(default=False, verbose_name='Доступ в админ панель'),
        ),
    ]
