# Generated by Django 4.1.5 on 2023-03-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.TextField(blank=True, null=True, verbose_name='Корзина'),
        ),
    ]
