# Generated by Django 4.1.5 on 2023-04-03 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название объявления')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/image', verbose_name='Фотография')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('email', models.CharField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('status', models.CharField(blank=True, choices=[('А', 'Активен'), ('Н', 'Неактивен')], max_length=255, null=True, verbose_name='Статус товара')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Доска',
                'verbose_name_plural': 'Доски',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='board.board', verbose_name='Товары')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='board.category', verbose_name='Категория'),
        ),
    ]
